### ISSUE TITLE
Выдает ошибку при указании страницы начала (без указания диапазона на том же деле работает нормально)

### ISSUE THREAD

**Issue by davidsgithubacc** [okolobaxa/cgamos-downloader#1]
![image](https://user-images.githubusercontent.com/93673118/140136988-285c04c9-3163-4ab9-af05-6b17b73a1243.png)

**Comment by davidsgithubacc** [comment]
Добавлю, что запуск из консоли "cgamos -f 203 -o 780 -d 4326 -s 150 -e 206 -p /Users/..."  - работает
п.с. Спасибо за программу!

**Comment by okolobaxa** [comment]
Спасибо за багрепорт, в ближайшее время исправлю

**Comment by okolobaxa** [comment]
Исправлено в версии 1.3
