### ISSUE TITLE
Собранные версии 1.3-1.8 не запускаются в Win7.

### ISSUE THREAD

**Issue by xxxxxxbox** [okolobaxa/cgamos-downloader#4]
Скомпилированная версия 1.8 не запускается в Windows 7x64.
Ошибка "Запуск программы невозможен, так как на компьютере отсутствует api-ms-win-core-winrt-l1-1-0.dll. Попробуйте переустановить программу".
см. скриншот

Попробовал запустить другие версии на этом же компьютере. 
v1.7 - не запускается с аналогичной ошибкой
v1.3 - не запускается с аналогичной ошибкой
v1.2 - запускается, открывается консоль. Можно ввести номер фонда, описи, дела. Если не вводить номера страниц, то закачка стартует нормально. Если ввести стартовую страницу (1) , то после нажатия на Enter в консоли выдается многострочная ошибка - см. скриншот и происходит выход из программы.
v1.1. - на том же компьютере запускается и работает нормально. Файлы скачиваются при вводе тех же данных, что и в v 1.2. 

Раньше я такого за программой не замечал, хотя я не тестировал каждую версию и не тестировал все возможные варианты задавания параметров.  Возможно ошибка проявляется только на отдельном компьютере из-за каких-то особенностей программного окружения. Может быть при сборке версий, начиная с 1.3 какая-то библиотека не подцепляется...  Старые версии лечить смысла нет, если в новых версиях ошибки не воспроизводятся. Информацию о них привел для того, чтобы показать, когда примерно появилась проблема, а также показать, что в ранних версиях ее не было.
![cgamos-not-starting v1 3-1 8](https://user-images.githubusercontent.com/56993366/152100989-b7a1e7ec-7c8d-447a-b52e-5eb3cc4be912.JPG)

![cgamos-1 2](https://user-images.githubusercontent.com/56993366/152100997-2ed694d4-e991-4276-9f90-b25b3c9f1250.JPG)

![cgamos-1_1](https://user-images.githubusercontent.com/56993366/152102133-db1de7f0-91d3-4064-ad13-9ea9aee91d5a.JPG)

**Comment by okolobaxa** [comment]
Начиная с версии v1.3 программа собиралась на .NET6
Попробуйте поставить последние Microsoft Visual C++ Redistributable packages отсюда https://aka.ms/vs/17/release/vc_redist.x64.exe

К сожалению нет Win7 чтобы проверить. Если не взлетит - поставлю на виртуалку и попробую что-то придумать.

**Comment by xxxxxxbox** [comment]
Вероятную причину я нашел в интернете. 

Вот здесь обсуждают:
[https://steamcommunity.com/groups/archiasf/discussions/8/3198115500348900648/](url)
[https://steamcommunity.com/groups/archiasf/discussions/8/3198115500348900648/](url)

Как я понял, нормального решения нет. Если решать со стороны пользователя, то остается либо обновлять операционную систему до Win8+, либо подкладывать DLL из Win8 (что не рекомендуют). На стороне "сборщика" можно что-нибудь придумать, но этим нужно специально озадачиться и не уверен, что стоит под отдельную программу перенастраивать свою рабочую среду и тратить на решение время. 

Я свою проблему при необходимости решу. У меня есть возможность запустить программу на Win10.
Но в целом, для обычного пользователя, который скачает программу и попробует запустить ее на Win7, она не запустится.

Можно указать в системных требованиях операционную систему Win8+ и оставить, как есть.

**Comment by okolobaxa** [comment]
На стороне сборщика только один вариант - откатить до .NET 5, чего я делать не хочу.
